allowBuilds:
  esbuild: true
packages:
  - '../packages/dsh-maestro-remote'
  - '../packages/dsh-maestro-review'
  - '../packages/dsh-maestro-govard'
  - '../packages/dsh-maestro-memory'
  - '../packages/dsh-maestro-mobile'
  - '../packages/dsh-maestro-notifier'
  - '../packages/dsh-maestro-config'
  - '../packages/dsh-maestro-dashboard'
  - '../packages/dsh-maestro-sync'
  - '../packages/dsh-maestro-config-lib'
  - '../maestro-skills'
overrides:
  '@deepseek-ai/dsh-sandbox-policy@>=0.1.1': 0.1.1-rc.2
  '@deepseek-ai/dsh-sandbox@>=0.1.1': 0.1.1-rc.2
  '@deepseek-ai/dsh-invariants': 0.1.1-rc.2
minimumReleaseAgeExclude:
  - '@ddtcorex/dsh-maestro-config-lib@0.1.2'
  - '@deepseek-ai/cosmokit@1.8.3'
  - '@deepseek-ai/dsh-agent-default-model@0.1.2-alpha.2'
  - '@deepseek-ai/dsh-agent-presets@0.1.2-alpha.2'
  - '@deepseek-ai/dsh-agent@0.1.2-alpha.2'
  - '@deepseek-ai/dsh-brand@0.1.2-alpha.2'
  - '@deepseek-ai/dsh-client-connection@0.1.2-alpha.2'
  - '@deepseek-ai/dsh-client-ui-slots@0.1.2-alpha.2'
  - '@deepseek-ai/dsh-credentials@0.1.2-alpha.2'
  - '@deepseek-ai/dsh-llm@0.1.2-alpha.2'
  - '@deepseek-ai/dsh-session-title@0.1.2-alpha.2'
  - '@deepseek-ai/dsh-session@0.1.2-alpha.2'
  - '@deepseek-ai/dsh-subagent@0.1.2-alpha.2'
  - '@deepseek-ai/dsh-timeout@0.1.2-alpha.2'
  - '@deepseek-ai/dsh-tools@0.1.2-alpha.2'
  - '@deepseek-ai/dsh-typert-protocol@0.1.2-alpha.2'
  - '@deepseek-ai/dsh-util-crypto@0.1.2-alpha.2'
  - '@deepseek-ai/dsh-util-time@0.1.2-alpha.2'
  - '@deepseek-ai/dsh-util-values@0.1.2-alpha.2'
  - '@deepseek-ai/schemastery@3.18.2'
